name: Shelly Recorder Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Define the repository for the Docker image
  repository: ghcr.io/gbolabs/shelly-recorder

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: src/api/
      run: docker build --file Dockerfile-shelly-recorder --tag ${{ env.repository }}:$(date +'%Y%m%d')-${{ github.run_number}} \
        --tag ${{ env.repository }}:latest --tag ${{ env.repository }}:$(date +'%Y%m%d') .
    - name: Push the Docker image
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push the Docker image
      run: docker push ${{ env.repository }}:$(date +'%Y%m%d')-${{ github.run_number}} && \
           docker push ${{ env.repository }}:latest && \
           docker push ${{ env.repository }}:$(date +'%Y%m%d')
