name: Shelly Recorder Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: src/api/
      run: docker build . --file Dockerfile-shelly-recorder --tag ghcr.io/evload-report/shelly-recorder:$(date +%Y%m%d%H%M%S)
    - name: Push the Docker image
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push the Docker image
      run: docker push ghcr.io/evload-report/shelly-recorder:$(date +%Y%m%d%H%M%S)
